#!/home/david/P-<3/bin/python3

# --- IMPORTS ---

import json
import sys
import os
import numpy as np
from skimage.io import (
    imread,
    imsave,
)


# --- FUNCTIONS ---

def read(filename):
    img = imread(filename)
    return img 


def write(filename, img):
    imsave(filename, img)


def blur(img):
    pass


# --- SCRIPT ---

if __name__ == "__main__":
    filename_in = sys.argv[1]
    filename_out = sys.argv[2]
    img = read(filename)
    blured_img = blur(img)
    write(blured_img, filename_out)
